---
- name: fetch nvm installer
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
- name: install node.js
  shell: ". ~/.nvm/nvm.sh && nvm install {{nodejs_version}}"
- name: set global version of node.js
  shell: ". ~/.nvm/nvm.sh && nvm alias default {{nodejs_version}}"
