---
- hosts: localhost
  connection: local
  become: no
  roles:
    - nvm
    - homebrew-cask
    - homebrew
    - mas
    - fzf
  vars:
    nodejs_version: 20
    homebrew_packages:
      - vim
      - jq
      - gnu-sed
      - go
      - php@8.2
      - nkf
      - tree
      - awscli
      - sqlite
      - mas
      - mysql
      - awslogs
      - siege
      - make
      - libressl
      - curl
      - openjdk
      - percona-toolkit
      - graphviz
      - coreutils
      - aws-vault
      - font-udev-gothic-hs
    homebrew_cask_packages:
      - docker
      - slack
      - intellij-idea
      - discord
      - licecap
      - session-manager-plugin
      - sequel-ace
    mac_apps:
      - 409183694 # Keynote
      - 302584613 # Kindle
