---
- hosts: localhost
  connection: local
  become: no
  roles:
    - nvm
    - homebrew-cask
    - homebrew
    - mas
    - dotfiles
    - composer
    - fzf
  vars:
    nvm_version: 0.34.0
    nodejs_version: 12
    homebrew_packages:
      - vim
      - jq
      - gnu-sed
      - go
      - php@8.2
      - nkf
      - the_platinum_searcher
      - tree
      - awscli
      - lastpass-cli
      - sqlite
      - mas
      - typescript
      - mysql
      - sbt
      - ta-lib
      - awslogs
      - siege
      - telnet
      - make
      - redis
      - libressl
      - curl
      - openjdk
      - percona-toolkit
      - graphviz
    homebrew_cask_packages:
      - docker
      - slack
      - atom
      - skitch
      - intellij-idea
      - evernote
      - kindle
      - discord
      - licecap
    mac_apps:
      - 539883307
      - 409183694
