---
- name: create Homebrew dir
  file:
    state=directory
    dest=/Library/Homebrew
  become: yes
- name: install packages
  homebrew: name={{ item }} state=present
  with_items: "{{ homebrew_packages }}"
